# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oscilloscope_settings.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OscSettings(object):
    def setupUi(self, OscSettings):
        OscSettings.setObjectName("OscSettings")
        OscSettings.resize(502, 286)
        self.verticalLayout = QtWidgets.QVBoxLayout(OscSettings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(OscSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.tabWidget = QtWidgets.QTabWidget(OscSettings)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formWidget_3 = QtWidgets.QWidget(self.tab)
        self.formWidget_3.setObjectName("formWidget_3")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formWidget_3)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_13 = QtWidgets.QLabel(self.formWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.trigger_source = QtWidgets.QComboBox(self.formWidget_3)
        self.trigger_source.setMinimumSize(QtCore.QSize(200, 0))
        self.trigger_source.setObjectName("trigger_source")
        self.trigger_source.addItem("")
        self.trigger_source.addItem("")
        self.trigger_source.addItem("")
        self.trigger_source.addItem("")
        self.trigger_source.addItem("")
        self.trigger_source.addItem("")
        self.trigger_source.addItem("")
        self.trigger_source.addItem("")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.trigger_source)
        self.label_14 = QtWidgets.QLabel(self.formWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.formWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.trigger_sweep = QtWidgets.QComboBox(self.formWidget_3)
        self.trigger_sweep.setMinimumSize(QtCore.QSize(200, 0))
        self.trigger_sweep.setObjectName("trigger_sweep")
        self.trigger_sweep.addItem("")
        self.trigger_sweep.addItem("")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.trigger_sweep)
        self.label_16 = QtWidgets.QLabel(self.formWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.trigger_n_reject = QtWidgets.QCheckBox(self.formWidget_3)
        self.trigger_n_reject.setChecked(True)
        self.trigger_n_reject.setObjectName("trigger_n_reject")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.trigger_n_reject)
        self.trigger_hf_reject = QtWidgets.QCheckBox(self.formWidget_3)
        self.trigger_hf_reject.setChecked(True)
        self.trigger_hf_reject.setObjectName("trigger_hf_reject")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.trigger_hf_reject)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.trigger_level = QtWidgets.QDoubleSpinBox(self.formWidget_3)
        self.trigger_level.setMinimumSize(QtCore.QSize(200, 0))
        self.trigger_level.setAlignment(QtCore.Qt.AlignCenter)
        self.trigger_level.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.trigger_level.setDecimals(3)
        self.trigger_level.setMinimum(-10.0)
        self.trigger_level.setMaximum(10.0)
        self.trigger_level.setObjectName("trigger_level")
        self.verticalLayout_4.addWidget(self.trigger_level)
        self.formLayout_5.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_4)
        self.trigger_slope = QtWidgets.QComboBox(self.formWidget_3)
        self.trigger_slope.setMinimumSize(QtCore.QSize(200, 0))
        self.trigger_slope.setObjectName("trigger_slope")
        self.trigger_slope.addItem("")
        self.trigger_slope.addItem("")
        self.trigger_slope.addItem("")
        self.trigger_slope.addItem("")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.trigger_slope)
        self.verticalLayout_2.addWidget(self.formWidget_3, 0, QtCore.Qt.AlignVCenter)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formWidget_2 = QtWidgets.QWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formWidget_2.sizePolicy().hasHeightForWidth())
        self.formWidget_2.setSizePolicy(sizePolicy)
        self.formWidget_2.setObjectName("formWidget_2")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formWidget_2)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_10 = QtWidgets.QLabel(self.formWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.bw = QtWidgets.QCheckBox(self.formWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bw.sizePolicy().hasHeightForWidth())
        self.bw.setSizePolicy(sizePolicy)
        self.bw.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.bw.setText("")
        self.bw.setChecked(True)
        self.bw.setTristate(False)
        self.bw.setObjectName("bw")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.bw)
        self.label_11 = QtWidgets.QLabel(self.formWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.coupling = QtWidgets.QComboBox(self.formWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coupling.sizePolicy().hasHeightForWidth())
        self.coupling.setSizePolicy(sizePolicy)
        self.coupling.setMinimumSize(QtCore.QSize(200, 0))
        self.coupling.setObjectName("coupling")
        self.coupling.addItem("")
        self.coupling.addItem("")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.coupling)
        self.label_12 = QtWidgets.QLabel(self.formWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.probe = QtWidgets.QComboBox(self.formWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.probe.sizePolicy().hasHeightForWidth())
        self.probe.setSizePolicy(sizePolicy)
        self.probe.setMinimumSize(QtCore.QSize(200, 0))
        self.probe.setObjectName("probe")
        self.probe.addItem("")
        self.probe.addItem("")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.probe)
        self.verticalLayout_5.addWidget(self.formWidget_2, 0, QtCore.Qt.AlignVCenter)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalWidget = QtWidgets.QWidget(OscSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget.sizePolicy().hasHeightForWidth())
        self.horizontalWidget.setSizePolicy(sizePolicy)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.code = QtWidgets.QLabel(self.horizontalWidget)
        self.code.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.code.setFont(font)
        self.code.setObjectName("code")
        self.horizontalLayout_2.addWidget(self.code)
        self.status = QtWidgets.QLabel(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status.sizePolicy().hasHeightForWidth())
        self.status.setSizePolicy(sizePolicy)
        self.status.setObjectName("status")
        self.horizontalLayout_2.addWidget(self.status)
        self.horizontalLayout_3.addWidget(self.horizontalWidget, 0, QtCore.Qt.AlignLeft)
        self.horizontalWidget1 = QtWidgets.QWidget(OscSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget1.sizePolicy().hasHeightForWidth())
        self.horizontalWidget1.setSizePolicy(sizePolicy)
        self.horizontalWidget1.setObjectName("horizontalWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.apply = QtWidgets.QPushButton(self.horizontalWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apply.sizePolicy().hasHeightForWidth())
        self.apply.setSizePolicy(sizePolicy)
        self.apply.setObjectName("apply")
        self.horizontalLayout.addWidget(self.apply)
        self.ok = QtWidgets.QPushButton(self.horizontalWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok.sizePolicy().hasHeightForWidth())
        self.ok.setSizePolicy(sizePolicy)
        self.ok.setObjectName("ok")
        self.horizontalLayout.addWidget(self.ok, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_3.addWidget(self.horizontalWidget1, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(OscSettings)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(OscSettings)

    def retranslateUi(self, OscSettings):
        _translate = QtCore.QCoreApplication.translate
        OscSettings.setWindowTitle(_translate("OscSettings", "Dialog"))
        self.label.setText(_translate("OscSettings", "Oscilloscope Settings"))
        self.label_13.setText(_translate("OscSettings", "Trigger Source"))
        self.trigger_source.setItemText(0, _translate("OscSettings", "Channel 1"))
        self.trigger_source.setItemText(1, _translate("OscSettings", "Channel 2"))
        self.trigger_source.setItemText(2, _translate("OscSettings", "Channel 3"))
        self.trigger_source.setItemText(3, _translate("OscSettings", "Channel 4"))
        self.trigger_source.setItemText(4, _translate("OscSettings", "Channel 5"))
        self.trigger_source.setItemText(5, _translate("OscSettings", "Channel 6"))
        self.trigger_source.setItemText(6, _translate("OscSettings", "External"))
        self.trigger_source.setItemText(7, _translate("OscSettings", "Line"))
        self.label_14.setText(_translate("OscSettings", "Trigger Slope"))
        self.label_15.setText(_translate("OscSettings", "Trigger Sweep"))
        self.trigger_sweep.setItemText(0, _translate("OscSettings", "Auto"))
        self.trigger_sweep.setItemText(1, _translate("OscSettings", "Normal"))
        self.label_16.setText(_translate("OscSettings", "Trigger Level"))
        self.trigger_n_reject.setText(_translate("OscSettings", "NReject"))
        self.trigger_hf_reject.setText(_translate("OscSettings", "HFReject"))
        self.trigger_slope.setItemText(0, _translate("OscSettings", "Positive"))
        self.trigger_slope.setItemText(1, _translate("OscSettings", "Negative"))
        self.trigger_slope.setItemText(2, _translate("OscSettings", "Either"))
        self.trigger_slope.setItemText(3, _translate("OscSettings", "Alternate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("OscSettings", "Trigger"))
        self.label_10.setText(_translate("OscSettings", "Bandwidth Limit"))
        self.label_11.setText(_translate("OscSettings", "Coupling"))
        self.coupling.setItemText(0, _translate("OscSettings", "DC"))
        self.coupling.setItemText(1, _translate("OscSettings", "AC"))
        self.label_12.setText(_translate("OscSettings", "Probe"))
        self.probe.setItemText(0, _translate("OscSettings", "10"))
        self.probe.setItemText(1, _translate("OscSettings", "1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("OscSettings", "Channel"))
        self.code.setText(_translate("OscSettings", "Status:"))
        self.status.setText(_translate("OscSettings", "All changes have been saved."))
        self.apply.setText(_translate("OscSettings", "Apply"))
        self.ok.setText(_translate("OscSettings", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OscSettings = QtWidgets.QDialog()
    ui = Ui_OscSettings()
    ui.setupUi(OscSettings)
    OscSettings.show()
    sys.exit(app.exec_())

