# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generator_settings.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GeneratorSettings(object):
    def setupUi(self, GeneratorSettings):
        GeneratorSettings.setObjectName("GeneratorSettings")
        GeneratorSettings.resize(509, 311)
        self.verticalLayout = QtWidgets.QVBoxLayout(GeneratorSettings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(GeneratorSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.formWidget = QtWidgets.QWidget(GeneratorSettings)
        self.formWidget.setObjectName("formWidget")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formWidget)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_17 = QtWidgets.QLabel(self.formWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.generator_vpp = QtWidgets.QDoubleSpinBox(self.formWidget)
        self.generator_vpp.setMinimumSize(QtCore.QSize(200, 0))
        self.generator_vpp.setAlignment(QtCore.Qt.AlignCenter)
        self.generator_vpp.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.generator_vpp.setDecimals(3)
        self.generator_vpp.setMaximum(20.0)
        self.generator_vpp.setProperty("value", 20.0)
        self.generator_vpp.setObjectName("generator_vpp")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.generator_vpp)
        self.label_23 = QtWidgets.QLabel(self.formWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.establishment_time = QtWidgets.QDoubleSpinBox(self.formWidget)
        self.establishment_time.setMinimumSize(QtCore.QSize(200, 0))
        self.establishment_time.setAlignment(QtCore.Qt.AlignCenter)
        self.establishment_time.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.establishment_time.setDecimals(3)
        self.establishment_time.setMaximum(10.0)
        self.establishment_time.setProperty("value", 0.1)
        self.establishment_time.setObjectName("establishment_time")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.establishment_time)
        self.label_20 = QtWidgets.QLabel(self.formWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.start_frequency = QtWidgets.QDoubleSpinBox(self.formWidget)
        self.start_frequency.setMinimumSize(QtCore.QSize(200, 0))
        self.start_frequency.setAlignment(QtCore.Qt.AlignCenter)
        self.start_frequency.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.start_frequency.setDecimals(0)
        self.start_frequency.setMinimum(1.0)
        self.start_frequency.setMaximum(1000000.0)
        self.start_frequency.setProperty("value", 100.0)
        self.start_frequency.setObjectName("start_frequency")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.start_frequency)
        self.label_21 = QtWidgets.QLabel(self.formWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.stop_frequency = QtWidgets.QDoubleSpinBox(self.formWidget)
        self.stop_frequency.setMinimumSize(QtCore.QSize(200, 0))
        self.stop_frequency.setAlignment(QtCore.Qt.AlignCenter)
        self.stop_frequency.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.stop_frequency.setDecimals(0)
        self.stop_frequency.setMinimum(1.0)
        self.stop_frequency.setMaximum(1000000.0)
        self.stop_frequency.setProperty("value", 100000.0)
        self.stop_frequency.setObjectName("stop_frequency")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.stop_frequency)
        self.label_22 = QtWidgets.QLabel(self.formWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.samples = QtWidgets.QSpinBox(self.formWidget)
        self.samples.setMinimumSize(QtCore.QSize(200, 0))
        self.samples.setAlignment(QtCore.Qt.AlignCenter)
        self.samples.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.samples.setMinimum(1)
        self.samples.setMaximum(1000)
        self.samples.setProperty("value", 25)
        self.samples.setObjectName("samples")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.samples)
        self.label_19 = QtWidgets.QLabel(self.formWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.scale = QtWidgets.QComboBox(self.formWidget)
        self.scale.setMinimumSize(QtCore.QSize(200, 0))
        self.scale.setObjectName("scale")
        self.scale.addItem("")
        self.scale.addItem("")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.scale)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout_6.setItem(2, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.verticalLayout.addWidget(self.formWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalWidget = QtWidgets.QWidget(GeneratorSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget.sizePolicy().hasHeightForWidth())
        self.horizontalWidget.setSizePolicy(sizePolicy)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.code = QtWidgets.QLabel(self.horizontalWidget)
        self.code.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.code.setFont(font)
        self.code.setObjectName("code")
        self.horizontalLayout_2.addWidget(self.code)
        self.status = QtWidgets.QLabel(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status.sizePolicy().hasHeightForWidth())
        self.status.setSizePolicy(sizePolicy)
        self.status.setObjectName("status")
        self.horizontalLayout_2.addWidget(self.status)
        self.horizontalLayout_3.addWidget(self.horizontalWidget, 0, QtCore.Qt.AlignLeft)
        self.horizontalWidget_2 = QtWidgets.QWidget(GeneratorSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget_2.sizePolicy().hasHeightForWidth())
        self.horizontalWidget_2.setSizePolicy(sizePolicy)
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.apply = QtWidgets.QPushButton(self.horizontalWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apply.sizePolicy().hasHeightForWidth())
        self.apply.setSizePolicy(sizePolicy)
        self.apply.setObjectName("apply")
        self.horizontalLayout.addWidget(self.apply)
        self.ok = QtWidgets.QPushButton(self.horizontalWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok.sizePolicy().hasHeightForWidth())
        self.ok.setSizePolicy(sizePolicy)
        self.ok.setObjectName("ok")
        self.horizontalLayout.addWidget(self.ok, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_3.addWidget(self.horizontalWidget_2, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(GeneratorSettings)
        QtCore.QMetaObject.connectSlotsByName(GeneratorSettings)

    def retranslateUi(self, GeneratorSettings):
        _translate = QtCore.QCoreApplication.translate
        GeneratorSettings.setWindowTitle(_translate("GeneratorSettings", "Dialog"))
        self.label.setText(_translate("GeneratorSettings", "Generator Settings"))
        self.label_17.setText(_translate("GeneratorSettings", "Input Peak to Peak (VPP)"))
        self.label_23.setText(_translate("GeneratorSettings", "Establishment Time (s)"))
        self.label_20.setText(_translate("GeneratorSettings", "Start Frequency (Hz)"))
        self.label_21.setText(_translate("GeneratorSettings", "Stop Frequency (Hz)"))
        self.label_22.setText(_translate("GeneratorSettings", "Number of samples"))
        self.label_19.setText(_translate("GeneratorSettings", "Scale"))
        self.scale.setItemText(0, _translate("GeneratorSettings", "Log"))
        self.scale.setItemText(1, _translate("GeneratorSettings", "Linear"))
        self.code.setText(_translate("GeneratorSettings", "Status:"))
        self.status.setText(_translate("GeneratorSettings", "All changes have been saved."))
        self.apply.setText(_translate("GeneratorSettings", "Apply"))
        self.ok.setText(_translate("GeneratorSettings", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GeneratorSettings = QtWidgets.QDialog()
    ui = Ui_GeneratorSettings()
    ui.setupUi(GeneratorSettings)
    GeneratorSettings.show()
    sys.exit(app.exec_())

