# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LabToolWindow(object):
    def setupUi(self, LabToolWindow):
        LabToolWindow.setObjectName("LabToolWindow")
        LabToolWindow.resize(471, 386)
        self.centralwidget = QtWidgets.QWidget(LabToolWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.device_page = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.device_page.sizePolicy().hasHeightForWidth())
        self.device_page.setSizePolicy(sizePolicy)
        self.device_page.setObjectName("device_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.device_page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.device_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(self.device_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.device_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.device_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.generatorList = QtWidgets.QComboBox(self.device_page)
        self.generatorList.setObjectName("generatorList")
        self.gridLayout.addWidget(self.generatorList, 1, 2, 1, 1)
        self.oscilloscopeList = QtWidgets.QComboBox(self.device_page)
        self.oscilloscopeList.setObjectName("oscilloscopeList")
        self.gridLayout.addWidget(self.oscilloscopeList, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.refreshButton = QtWidgets.QPushButton(self.device_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refreshButton.sizePolicy().hasHeightForWidth())
        self.refreshButton.setSizePolicy(sizePolicy)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout_2.addWidget(self.refreshButton, 0, QtCore.Qt.AlignRight)
        self.connectionButton = QtWidgets.QPushButton(self.device_page)
        self.connectionButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectionButton.sizePolicy().hasHeightForWidth())
        self.connectionButton.setSizePolicy(sizePolicy)
        self.connectionButton.setObjectName("connectionButton")
        self.horizontalLayout_2.addWidget(self.connectionButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.stackedWidget.addWidget(self.device_page)
        self.setting_page = QtWidgets.QWidget()
        self.setting_page.setObjectName("setting_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.setting_page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.setting_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.tabWidget = QtWidgets.QTabWidget(self.setting_page)
        self.tabWidget.setObjectName("tabWidget")
        self.input_channel = QtWidgets.QWidget()
        self.input_channel.setObjectName("input_channel")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.input_channel)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.formWidget = QtWidgets.QWidget(self.input_channel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formWidget.sizePolicy().hasHeightForWidth())
        self.formWidget.setSizePolicy(sizePolicy)
        self.formWidget.setObjectName("formWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formWidget)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.formWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.inputBandwidth = QtWidgets.QCheckBox(self.formWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputBandwidth.sizePolicy().hasHeightForWidth())
        self.inputBandwidth.setSizePolicy(sizePolicy)
        self.inputBandwidth.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.inputBandwidth.setText("")
        self.inputBandwidth.setTristate(False)
        self.inputBandwidth.setObjectName("inputBandwidth")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inputBandwidth)
        self.label_8 = QtWidgets.QLabel(self.formWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.formWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.inputCoupling = QtWidgets.QComboBox(self.formWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputCoupling.sizePolicy().hasHeightForWidth())
        self.inputCoupling.setSizePolicy(sizePolicy)
        self.inputCoupling.setMinimumSize(QtCore.QSize(200, 0))
        self.inputCoupling.setObjectName("inputCoupling")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.inputCoupling)
        self.inputProbe = QtWidgets.QComboBox(self.formWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputProbe.sizePolicy().hasHeightForWidth())
        self.inputProbe.setSizePolicy(sizePolicy)
        self.inputProbe.setMinimumSize(QtCore.QSize(200, 0))
        self.inputProbe.setObjectName("inputProbe")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.inputProbe)
        self.verticalLayout_6.addWidget(self.formWidget, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.tabWidget.addTab(self.input_channel, "")
        self.output_channel = QtWidgets.QWidget()
        self.output_channel.setObjectName("output_channel")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.output_channel)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.formWidget_2 = QtWidgets.QWidget(self.output_channel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formWidget_2.sizePolicy().hasHeightForWidth())
        self.formWidget_2.setSizePolicy(sizePolicy)
        self.formWidget_2.setObjectName("formWidget_2")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formWidget_2)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_10 = QtWidgets.QLabel(self.formWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.outputBandwidth = QtWidgets.QCheckBox(self.formWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputBandwidth.sizePolicy().hasHeightForWidth())
        self.outputBandwidth.setSizePolicy(sizePolicy)
        self.outputBandwidth.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.outputBandwidth.setText("")
        self.outputBandwidth.setTristate(False)
        self.outputBandwidth.setObjectName("outputBandwidth")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.outputBandwidth)
        self.label_11 = QtWidgets.QLabel(self.formWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.formWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.outputCoupling = QtWidgets.QComboBox(self.formWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputCoupling.sizePolicy().hasHeightForWidth())
        self.outputCoupling.setSizePolicy(sizePolicy)
        self.outputCoupling.setMinimumSize(QtCore.QSize(200, 0))
        self.outputCoupling.setObjectName("outputCoupling")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.outputCoupling)
        self.outputProbe = QtWidgets.QComboBox(self.formWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputProbe.sizePolicy().hasHeightForWidth())
        self.outputProbe.setSizePolicy(sizePolicy)
        self.outputProbe.setMinimumSize(QtCore.QSize(200, 0))
        self.outputProbe.setObjectName("outputProbe")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.outputProbe)
        self.verticalLayout_7.addWidget(self.formWidget_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.tabWidget.addTab(self.output_channel, "")
        self.trigger = QtWidgets.QWidget()
        self.trigger.setObjectName("trigger")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.trigger)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.formWidget_3 = QtWidgets.QWidget(self.trigger)
        self.formWidget_3.setObjectName("formWidget_3")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formWidget_3)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_13 = QtWidgets.QLabel(self.formWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.formWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.formWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(self.formWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.triggerSource = QtWidgets.QComboBox(self.formWidget_3)
        self.triggerSource.setMinimumSize(QtCore.QSize(200, 0))
        self.triggerSource.setObjectName("triggerSource")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.triggerSource)
        self.triggerSlope = QtWidgets.QComboBox(self.formWidget_3)
        self.triggerSlope.setMinimumSize(QtCore.QSize(200, 0))
        self.triggerSlope.setObjectName("triggerSlope")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.triggerSlope)
        self.triggerSweep = QtWidgets.QComboBox(self.formWidget_3)
        self.triggerSweep.setMinimumSize(QtCore.QSize(200, 0))
        self.triggerSweep.setObjectName("triggerSweep")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.triggerSweep)
        self.triggerLevel = QtWidgets.QDoubleSpinBox(self.formWidget_3)
        self.triggerLevel.setMinimumSize(QtCore.QSize(200, 0))
        self.triggerLevel.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.triggerLevel.setObjectName("triggerLevel")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.triggerLevel)
        self.hfReject = QtWidgets.QCheckBox(self.formWidget_3)
        self.hfReject.setObjectName("hfReject")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.hfReject)
        self.nReject = QtWidgets.QCheckBox(self.formWidget_3)
        self.nReject.setObjectName("nReject")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.nReject)
        self.verticalLayout_8.addWidget(self.formWidget_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.tabWidget.addTab(self.trigger, "")
        self.bode = QtWidgets.QWidget()
        self.bode.setObjectName("bode")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.bode)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.formWidget1 = QtWidgets.QWidget(self.bode)
        self.formWidget1.setObjectName("formWidget1")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formWidget1)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_17 = QtWidgets.QLabel(self.formWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtWidgets.QLabel(self.formWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtWidgets.QLabel(self.formWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.label_20 = QtWidgets.QLabel(self.formWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtWidgets.QLabel(self.formWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.label_22 = QtWidgets.QLabel(self.formWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.generatorVpp = QtWidgets.QDoubleSpinBox(self.formWidget1)
        self.generatorVpp.setMinimumSize(QtCore.QSize(200, 0))
        self.generatorVpp.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.generatorVpp.setObjectName("generatorVpp")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.generatorVpp)
        self.delay = QtWidgets.QDoubleSpinBox(self.formWidget1)
        self.delay.setMinimumSize(QtCore.QSize(200, 0))
        self.delay.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.delay.setObjectName("delay")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.delay)
        self.scale = QtWidgets.QComboBox(self.formWidget1)
        self.scale.setMinimumSize(QtCore.QSize(200, 0))
        self.scale.setObjectName("scale")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.scale)
        self.startFrequency = QtWidgets.QDoubleSpinBox(self.formWidget1)
        self.startFrequency.setMinimumSize(QtCore.QSize(200, 0))
        self.startFrequency.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.startFrequency.setObjectName("startFrequency")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.startFrequency)
        self.stopFrequency = QtWidgets.QDoubleSpinBox(self.formWidget1)
        self.stopFrequency.setMinimumSize(QtCore.QSize(200, 0))
        self.stopFrequency.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.stopFrequency.setObjectName("stopFrequency")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.stopFrequency)
        self.samples = QtWidgets.QSpinBox(self.formWidget1)
        self.samples.setMinimumSize(QtCore.QSize(200, 0))
        self.samples.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.samples.setObjectName("samples")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.samples)
        self.verticalLayout_9.addWidget(self.formWidget1, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.tabWidget.addTab(self.bode, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.backSettingButton = QtWidgets.QPushButton(self.setting_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backSettingButton.sizePolicy().hasHeightForWidth())
        self.backSettingButton.setSizePolicy(sizePolicy)
        self.backSettingButton.setObjectName("backSettingButton")
        self.horizontalLayout_3.addWidget(self.backSettingButton, 0, QtCore.Qt.AlignLeft)
        self.measureButton = QtWidgets.QPushButton(self.setting_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.measureButton.sizePolicy().hasHeightForWidth())
        self.measureButton.setSizePolicy(sizePolicy)
        self.measureButton.setObjectName("measureButton")
        self.horizontalLayout_3.addWidget(self.measureButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.stackedWidget.addWidget(self.setting_page)
        self.measure_page = QtWidgets.QWidget()
        self.measure_page.setObjectName("measure_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.measure_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.measure_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.previewBox = QtWidgets.QGroupBox(self.measure_page)
        self.previewBox.setObjectName("previewBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.previewBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.previewStack = QtWidgets.QStackedWidget(self.previewBox)
        self.previewStack.setObjectName("previewStack")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.previewStack.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.previewStack.addWidget(self.page_8)
        self.verticalLayout_5.addWidget(self.previewStack)
        self.verticalLayout_4.addWidget(self.previewBox)
        self.horizontalWidget_3 = QtWidgets.QWidget(self.measure_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget_3.sizePolicy().hasHeightForWidth())
        self.horizontalWidget_3.setSizePolicy(sizePolicy)
        self.horizontalWidget_3.setObjectName("horizontalWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalWidget_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.measureProgress = QtWidgets.QProgressBar(self.horizontalWidget_3)
        self.measureProgress.setProperty("value", 24)
        self.measureProgress.setObjectName("measureProgress")
        self.horizontalLayout_4.addWidget(self.measureProgress)
        self.backMeasureButton = QtWidgets.QPushButton(self.horizontalWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backMeasureButton.sizePolicy().hasHeightForWidth())
        self.backMeasureButton.setSizePolicy(sizePolicy)
        self.backMeasureButton.setObjectName("backMeasureButton")
        self.horizontalLayout_4.addWidget(self.backMeasureButton, 0, QtCore.Qt.AlignRight)
        self.stopButton = QtWidgets.QPushButton(self.horizontalWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_4.addWidget(self.stopButton, 0, QtCore.Qt.AlignRight)
        self.exportButton = QtWidgets.QPushButton(self.horizontalWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportButton.sizePolicy().hasHeightForWidth())
        self.exportButton.setSizePolicy(sizePolicy)
        self.exportButton.setObjectName("exportButton")
        self.horizontalLayout_4.addWidget(self.exportButton, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_4.addWidget(self.horizontalWidget_3)
        self.stackedWidget.addWidget(self.measure_page)
        self.verticalLayout.addWidget(self.stackedWidget)
        LabToolWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LabToolWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(LabToolWindow)

    def retranslateUi(self, LabToolWindow):
        _translate = QtCore.QCoreApplication.translate
        LabToolWindow.setWindowTitle(_translate("LabToolWindow", "MainWindow"))
        self.label_2.setText(_translate("LabToolWindow", "Device Connection"))
        self.label.setText(_translate("LabToolWindow", "You need to connect both an oscilloscope and a generator via USB, then update or refresh with the button and select for each device those that have been detected."))
        self.label_3.setText(_translate("LabToolWindow", "Oscilloscope Device"))
        self.label_4.setText(_translate("LabToolWindow", "Generator Device"))
        self.refreshButton.setText(_translate("LabToolWindow", "Refresh"))
        self.connectionButton.setText(_translate("LabToolWindow", "Next"))
        self.label_5.setText(_translate("LabToolWindow", "Measuring Settings"))
        self.label_7.setText(_translate("LabToolWindow", "Bandwidth Limit"))
        self.label_8.setText(_translate("LabToolWindow", "Coupling"))
        self.label_9.setText(_translate("LabToolWindow", "Probe"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.input_channel), _translate("LabToolWindow", "Input Channel (Vi)"))
        self.label_10.setText(_translate("LabToolWindow", "Bandwidth Limit"))
        self.label_11.setText(_translate("LabToolWindow", "Coupling"))
        self.label_12.setText(_translate("LabToolWindow", "Probe"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.output_channel), _translate("LabToolWindow", "Output Channel (Vo)"))
        self.label_13.setText(_translate("LabToolWindow", "Trigger Source"))
        self.label_14.setText(_translate("LabToolWindow", "Trigger Slope"))
        self.label_15.setText(_translate("LabToolWindow", " Trigger Sweep"))
        self.label_16.setText(_translate("LabToolWindow", "Trigger Level"))
        self.hfReject.setText(_translate("LabToolWindow", "HFReject"))
        self.nReject.setText(_translate("LabToolWindow", "NReject"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.trigger), _translate("LabToolWindow", "Trigger"))
        self.label_17.setText(_translate("LabToolWindow", "Input Peak to Peak (VPP)"))
        self.label_18.setText(_translate("LabToolWindow", "Delay (s)"))
        self.label_19.setText(_translate("LabToolWindow", "Scale"))
        self.label_20.setText(_translate("LabToolWindow", "Start Frequency (Hz)"))
        self.label_21.setText(_translate("LabToolWindow", "Stop Frequency (Hz)"))
        self.label_22.setText(_translate("LabToolWindow", "Number of samples"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.bode), _translate("LabToolWindow", "Bode Preferences"))
        self.backSettingButton.setText(_translate("LabToolWindow", "Back"))
        self.measureButton.setText(_translate("LabToolWindow", "Measure"))
        self.label_6.setText(_translate("LabToolWindow", "Measure Output"))
        self.previewBox.setTitle(_translate("LabToolWindow", "Preview"))
        self.backMeasureButton.setText(_translate("LabToolWindow", "Back"))
        self.stopButton.setText(_translate("LabToolWindow", "Stop"))
        self.exportButton.setText(_translate("LabToolWindow", "Export .xls"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LabToolWindow = QtWidgets.QMainWindow()
    ui = Ui_LabToolWindow()
    ui.setupUi(LabToolWindow)
    LabToolWindow.show()
    sys.exit(app.exec_())

