# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LabToolWindow(object):
    def setupUi(self, LabToolWindow):
        LabToolWindow.setObjectName("LabToolWindow")
        LabToolWindow.resize(629, 501)
        self.centralwidget = QtWidgets.QWidget(LabToolWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.device_page = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.device_page.sizePolicy().hasHeightForWidth())
        self.device_page.setSizePolicy(sizePolicy)
        self.device_page.setObjectName("device_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.device_page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.device_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(self.device_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.device_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.device_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.generators = QtWidgets.QComboBox(self.device_page)
        self.generators.setObjectName("generators")
        self.gridLayout.addWidget(self.generators, 1, 2, 1, 1)
        self.oscilloscopes = QtWidgets.QComboBox(self.device_page)
        self.oscilloscopes.setObjectName("oscilloscopes")
        self.gridLayout.addWidget(self.oscilloscopes, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.connection_status = QtWidgets.QLabel(self.device_page)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.connection_status.setFont(font)
        self.connection_status.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.connection_status.setWordWrap(True)
        self.connection_status.setObjectName("connection_status")
        self.gridLayout_3.addWidget(self.connection_status, 0, 0, 1, 1)
        self.refresh = QtWidgets.QPushButton(self.device_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refresh.sizePolicy().hasHeightForWidth())
        self.refresh.setSizePolicy(sizePolicy)
        self.refresh.setObjectName("refresh")
        self.gridLayout_3.addWidget(self.refresh, 0, 1, 1, 1)
        self.connection = QtWidgets.QPushButton(self.device_page)
        self.connection.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connection.sizePolicy().hasHeightForWidth())
        self.connection.setSizePolicy(sizePolicy)
        self.connection.setObjectName("connection")
        self.gridLayout_3.addWidget(self.connection, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.stackedWidget.addWidget(self.device_page)
        self.setting_page = QtWidgets.QWidget()
        self.setting_page.setObjectName("setting_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.setting_page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.setting_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.tabWidget = QtWidgets.QTabWidget(self.setting_page)
        self.tabWidget.setObjectName("tabWidget")
        self.input_channel = QtWidgets.QWidget()
        self.input_channel.setObjectName("input_channel")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.input_channel)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.formWidget = QtWidgets.QWidget(self.input_channel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formWidget.sizePolicy().hasHeightForWidth())
        self.formWidget.setSizePolicy(sizePolicy)
        self.formWidget.setObjectName("formWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formWidget)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.formWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.input_bw = QtWidgets.QCheckBox(self.formWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_bw.sizePolicy().hasHeightForWidth())
        self.input_bw.setSizePolicy(sizePolicy)
        self.input_bw.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.input_bw.setText("")
        self.input_bw.setChecked(True)
        self.input_bw.setTristate(False)
        self.input_bw.setObjectName("input_bw")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_bw)
        self.label_8 = QtWidgets.QLabel(self.formWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.formWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.input_coupling = QtWidgets.QComboBox(self.formWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_coupling.sizePolicy().hasHeightForWidth())
        self.input_coupling.setSizePolicy(sizePolicy)
        self.input_coupling.setMinimumSize(QtCore.QSize(200, 0))
        self.input_coupling.setObjectName("input_coupling")
        self.input_coupling.addItem("")
        self.input_coupling.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_coupling)
        self.input_probe = QtWidgets.QComboBox(self.formWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_probe.sizePolicy().hasHeightForWidth())
        self.input_probe.setSizePolicy(sizePolicy)
        self.input_probe.setMinimumSize(QtCore.QSize(200, 0))
        self.input_probe.setObjectName("input_probe")
        self.input_probe.addItem("")
        self.input_probe.addItem("")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.input_probe)
        self.label_24 = QtWidgets.QLabel(self.formWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.input_source = QtWidgets.QComboBox(self.formWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_source.sizePolicy().hasHeightForWidth())
        self.input_source.setSizePolicy(sizePolicy)
        self.input_source.setMinimumSize(QtCore.QSize(200, 0))
        self.input_source.setObjectName("input_source")
        self.input_source.addItem("")
        self.input_source.addItem("")
        self.input_source.addItem("")
        self.input_source.addItem("")
        self.input_source.addItem("")
        self.input_source.addItem("")
        self.input_source.addItem("")
        self.input_source.addItem("")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.input_source)
        self.verticalLayout_6.addWidget(self.formWidget, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.tabWidget.addTab(self.input_channel, "")
        self.output_channel = QtWidgets.QWidget()
        self.output_channel.setObjectName("output_channel")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.output_channel)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.formWidget_2 = QtWidgets.QWidget(self.output_channel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formWidget_2.sizePolicy().hasHeightForWidth())
        self.formWidget_2.setSizePolicy(sizePolicy)
        self.formWidget_2.setObjectName("formWidget_2")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formWidget_2)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_10 = QtWidgets.QLabel(self.formWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.output_bw = QtWidgets.QCheckBox(self.formWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_bw.sizePolicy().hasHeightForWidth())
        self.output_bw.setSizePolicy(sizePolicy)
        self.output_bw.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.output_bw.setText("")
        self.output_bw.setChecked(True)
        self.output_bw.setTristate(False)
        self.output_bw.setObjectName("output_bw")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.output_bw)
        self.label_11 = QtWidgets.QLabel(self.formWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.formWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.output_coupling = QtWidgets.QComboBox(self.formWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_coupling.sizePolicy().hasHeightForWidth())
        self.output_coupling.setSizePolicy(sizePolicy)
        self.output_coupling.setMinimumSize(QtCore.QSize(200, 0))
        self.output_coupling.setObjectName("output_coupling")
        self.output_coupling.addItem("")
        self.output_coupling.addItem("")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.output_coupling)
        self.output_probe = QtWidgets.QComboBox(self.formWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_probe.sizePolicy().hasHeightForWidth())
        self.output_probe.setSizePolicy(sizePolicy)
        self.output_probe.setMinimumSize(QtCore.QSize(200, 0))
        self.output_probe.setObjectName("output_probe")
        self.output_probe.addItem("")
        self.output_probe.addItem("")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.output_probe)
        self.label_25 = QtWidgets.QLabel(self.formWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.output_source = QtWidgets.QComboBox(self.formWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_source.sizePolicy().hasHeightForWidth())
        self.output_source.setSizePolicy(sizePolicy)
        self.output_source.setMinimumSize(QtCore.QSize(200, 0))
        self.output_source.setObjectName("output_source")
        self.output_source.addItem("")
        self.output_source.addItem("")
        self.output_source.addItem("")
        self.output_source.addItem("")
        self.output_source.addItem("")
        self.output_source.addItem("")
        self.output_source.addItem("")
        self.output_source.addItem("")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.output_source)
        self.verticalLayout_7.addWidget(self.formWidget_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.tabWidget.addTab(self.output_channel, "")
        self.trigger = QtWidgets.QWidget()
        self.trigger.setObjectName("trigger")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.trigger)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.formWidget_3 = QtWidgets.QWidget(self.trigger)
        self.formWidget_3.setObjectName("formWidget_3")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formWidget_3)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_13 = QtWidgets.QLabel(self.formWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.formWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.formWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(self.formWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.trigger_source = QtWidgets.QComboBox(self.formWidget_3)
        self.trigger_source.setMinimumSize(QtCore.QSize(200, 0))
        self.trigger_source.setObjectName("trigger_source")
        self.trigger_source.addItem("")
        self.trigger_source.addItem("")
        self.trigger_source.addItem("")
        self.trigger_source.addItem("")
        self.trigger_source.addItem("")
        self.trigger_source.addItem("")
        self.trigger_source.addItem("")
        self.trigger_source.addItem("")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.trigger_source)
        self.trigger_slope = QtWidgets.QComboBox(self.formWidget_3)
        self.trigger_slope.setMinimumSize(QtCore.QSize(200, 0))
        self.trigger_slope.setObjectName("trigger_slope")
        self.trigger_slope.addItem("")
        self.trigger_slope.addItem("")
        self.trigger_slope.addItem("")
        self.trigger_slope.addItem("")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.trigger_slope)
        self.trigger_sweep = QtWidgets.QComboBox(self.formWidget_3)
        self.trigger_sweep.setMinimumSize(QtCore.QSize(200, 0))
        self.trigger_sweep.setObjectName("trigger_sweep")
        self.trigger_sweep.addItem("")
        self.trigger_sweep.addItem("")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.trigger_sweep)
        self.trigger_level = QtWidgets.QDoubleSpinBox(self.formWidget_3)
        self.trigger_level.setMinimumSize(QtCore.QSize(200, 0))
        self.trigger_level.setAlignment(QtCore.Qt.AlignCenter)
        self.trigger_level.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.trigger_level.setDecimals(3)
        self.trigger_level.setMinimum(-10.0)
        self.trigger_level.setMaximum(10.0)
        self.trigger_level.setObjectName("trigger_level")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.trigger_level)
        self.trigger_hf_reject = QtWidgets.QCheckBox(self.formWidget_3)
        self.trigger_hf_reject.setChecked(True)
        self.trigger_hf_reject.setObjectName("trigger_hf_reject")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.trigger_hf_reject)
        self.trigger_n_reject = QtWidgets.QCheckBox(self.formWidget_3)
        self.trigger_n_reject.setChecked(True)
        self.trigger_n_reject.setObjectName("trigger_n_reject")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.trigger_n_reject)
        self.verticalLayout_8.addWidget(self.formWidget_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.tabWidget.addTab(self.trigger, "")
        self.bode = QtWidgets.QWidget()
        self.bode.setObjectName("bode")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.bode)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.formWidget1 = QtWidgets.QWidget(self.bode)
        self.formWidget1.setObjectName("formWidget1")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formWidget1)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_17 = QtWidgets.QLabel(self.formWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtWidgets.QLabel(self.formWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_20 = QtWidgets.QLabel(self.formWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtWidgets.QLabel(self.formWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.label_22 = QtWidgets.QLabel(self.formWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.generator_vpp = QtWidgets.QDoubleSpinBox(self.formWidget1)
        self.generator_vpp.setMinimumSize(QtCore.QSize(200, 0))
        self.generator_vpp.setAlignment(QtCore.Qt.AlignCenter)
        self.generator_vpp.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.generator_vpp.setDecimals(3)
        self.generator_vpp.setMaximum(20.0)
        self.generator_vpp.setProperty("value", 20.0)
        self.generator_vpp.setObjectName("generator_vpp")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.generator_vpp)
        self.delay = QtWidgets.QDoubleSpinBox(self.formWidget1)
        self.delay.setMinimumSize(QtCore.QSize(200, 0))
        self.delay.setAlignment(QtCore.Qt.AlignCenter)
        self.delay.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.delay.setDecimals(3)
        self.delay.setMaximum(10.0)
        self.delay.setProperty("value", 0.01)
        self.delay.setObjectName("delay")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.delay)
        self.start_frequency = QtWidgets.QDoubleSpinBox(self.formWidget1)
        self.start_frequency.setMinimumSize(QtCore.QSize(200, 0))
        self.start_frequency.setAlignment(QtCore.Qt.AlignCenter)
        self.start_frequency.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.start_frequency.setDecimals(2)
        self.start_frequency.setMinimum(1.0)
        self.start_frequency.setMaximum(1000000.0)
        self.start_frequency.setProperty("value", 100.0)
        self.start_frequency.setObjectName("start_frequency")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.start_frequency)
        self.stop_frequency = QtWidgets.QDoubleSpinBox(self.formWidget1)
        self.stop_frequency.setMinimumSize(QtCore.QSize(200, 0))
        self.stop_frequency.setAlignment(QtCore.Qt.AlignCenter)
        self.stop_frequency.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.stop_frequency.setDecimals(2)
        self.stop_frequency.setMinimum(1.0)
        self.stop_frequency.setMaximum(1000000.0)
        self.stop_frequency.setProperty("value", 100000.0)
        self.stop_frequency.setObjectName("stop_frequency")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.stop_frequency)
        self.samples = QtWidgets.QSpinBox(self.formWidget1)
        self.samples.setMinimumSize(QtCore.QSize(200, 0))
        self.samples.setAlignment(QtCore.Qt.AlignCenter)
        self.samples.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.samples.setMinimum(1)
        self.samples.setMaximum(1000)
        self.samples.setProperty("value", 25)
        self.samples.setObjectName("samples")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.samples)
        self.label_23 = QtWidgets.QLabel(self.formWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.establishment_time = QtWidgets.QDoubleSpinBox(self.formWidget1)
        self.establishment_time.setMinimumSize(QtCore.QSize(200, 0))
        self.establishment_time.setAlignment(QtCore.Qt.AlignCenter)
        self.establishment_time.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.establishment_time.setDecimals(3)
        self.establishment_time.setMaximum(10.0)
        self.establishment_time.setProperty("value", 0.1)
        self.establishment_time.setObjectName("establishment_time")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.establishment_time)
        self.label_19 = QtWidgets.QLabel(self.formWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.scale = QtWidgets.QComboBox(self.formWidget1)
        self.scale.setMinimumSize(QtCore.QSize(200, 0))
        self.scale.setObjectName("scale")
        self.scale.addItem("")
        self.scale.addItem("")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.scale)
        self.verticalLayout_9.addWidget(self.formWidget1, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.tabWidget.addTab(self.bode, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.settings_back = QtWidgets.QPushButton(self.setting_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_back.sizePolicy().hasHeightForWidth())
        self.settings_back.setSizePolicy(sizePolicy)
        self.settings_back.setObjectName("settings_back")
        self.gridLayout_2.addWidget(self.settings_back, 0, 0, 1, 1)
        self.setting_status = QtWidgets.QLabel(self.setting_page)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.setting_status.setFont(font)
        self.setting_status.setObjectName("setting_status")
        self.gridLayout_2.addWidget(self.setting_status, 0, 1, 1, 1)
        self.measure = QtWidgets.QPushButton(self.setting_page)
        self.measure.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.measure.sizePolicy().hasHeightForWidth())
        self.measure.setSizePolicy(sizePolicy)
        self.measure.setObjectName("measure")
        self.gridLayout_2.addWidget(self.measure, 0, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.stackedWidget.addWidget(self.setting_page)
        self.measure_page = QtWidgets.QWidget()
        self.measure_page.setObjectName("measure_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.measure_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.measure_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAutoFillBackground(True)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.previewBox = QtWidgets.QGroupBox(self.measure_page)
        self.previewBox.setObjectName("previewBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.previewBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.previewStack = QtWidgets.QStackedWidget(self.previewBox)
        self.previewStack.setObjectName("previewStack")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.previewStack.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.previewStack.addWidget(self.page_8)
        self.verticalLayout_5.addWidget(self.previewStack)
        self.verticalLayout_4.addWidget(self.previewBox)
        self.logger = QtWidgets.QTextEdit(self.measure_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logger.sizePolicy().hasHeightForWidth())
        self.logger.setSizePolicy(sizePolicy)
        self.logger.setMinimumSize(QtCore.QSize(0, 0))
        self.logger.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.logger.setFont(font)
        self.logger.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.logger.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.logger.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.logger.setObjectName("logger")
        self.verticalLayout_4.addWidget(self.logger)
        self.horizontalWidget_3 = QtWidgets.QWidget(self.measure_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget_3.sizePolicy().hasHeightForWidth())
        self.horizontalWidget_3.setSizePolicy(sizePolicy)
        self.horizontalWidget_3.setObjectName("horizontalWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalWidget_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.progress = QtWidgets.QProgressBar(self.horizontalWidget_3)
        self.progress.setProperty("value", 24)
        self.progress.setObjectName("progress")
        self.horizontalLayout_4.addWidget(self.progress)
        self.measure_back = QtWidgets.QPushButton(self.horizontalWidget_3)
        self.measure_back.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.measure_back.sizePolicy().hasHeightForWidth())
        self.measure_back.setSizePolicy(sizePolicy)
        self.measure_back.setObjectName("measure_back")
        self.horizontalLayout_4.addWidget(self.measure_back, 0, QtCore.Qt.AlignRight)
        self.stop = QtWidgets.QPushButton(self.horizontalWidget_3)
        self.stop.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop.sizePolicy().hasHeightForWidth())
        self.stop.setSizePolicy(sizePolicy)
        self.stop.setObjectName("stop")
        self.horizontalLayout_4.addWidget(self.stop, 0, QtCore.Qt.AlignRight)
        self.export_excel = QtWidgets.QPushButton(self.horizontalWidget_3)
        self.export_excel.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.export_excel.sizePolicy().hasHeightForWidth())
        self.export_excel.setSizePolicy(sizePolicy)
        self.export_excel.setObjectName("export_excel")
        self.horizontalLayout_4.addWidget(self.export_excel, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_4.addWidget(self.horizontalWidget_3)
        self.stackedWidget.addWidget(self.measure_page)
        self.verticalLayout.addWidget(self.stackedWidget)
        LabToolWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LabToolWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(3)
        self.output_source.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(LabToolWindow)

    def retranslateUi(self, LabToolWindow):
        _translate = QtCore.QCoreApplication.translate
        LabToolWindow.setWindowTitle(_translate("LabToolWindow", "MainWindow"))
        self.label_2.setText(_translate("LabToolWindow", "Device Connection"))
        self.label.setText(_translate("LabToolWindow", "You need to connect both an oscilloscope and a generator via USB, then update or refresh with the button and select for each device those that have been detected. Only supported devices will be detected."))
        self.label_3.setText(_translate("LabToolWindow", "Oscilloscope Device"))
        self.label_4.setText(_translate("LabToolWindow", "Generator Device"))
        self.connection_status.setText(_translate("LabToolWindow", "Remember using the Refresh button whenever you want to update the Device\'s lists."))
        self.refresh.setText(_translate("LabToolWindow", "Refresh"))
        self.connection.setText(_translate("LabToolWindow", "Next"))
        self.label_5.setText(_translate("LabToolWindow", "Measuring Settings"))
        self.label_7.setText(_translate("LabToolWindow", "Bandwidth Limit"))
        self.label_8.setText(_translate("LabToolWindow", "Coupling"))
        self.label_9.setText(_translate("LabToolWindow", "Probe"))
        self.input_coupling.setItemText(0, _translate("LabToolWindow", "DC"))
        self.input_coupling.setItemText(1, _translate("LabToolWindow", "AC"))
        self.input_probe.setItemText(0, _translate("LabToolWindow", "10"))
        self.input_probe.setItemText(1, _translate("LabToolWindow", "1"))
        self.label_24.setText(_translate("LabToolWindow", "Source"))
        self.input_source.setItemText(0, _translate("LabToolWindow", "Channel 1"))
        self.input_source.setItemText(1, _translate("LabToolWindow", "Channel 2"))
        self.input_source.setItemText(2, _translate("LabToolWindow", "Channel 3"))
        self.input_source.setItemText(3, _translate("LabToolWindow", "Channel 4"))
        self.input_source.setItemText(4, _translate("LabToolWindow", "Channel 5"))
        self.input_source.setItemText(5, _translate("LabToolWindow", "Channel 6"))
        self.input_source.setItemText(6, _translate("LabToolWindow", "External"))
        self.input_source.setItemText(7, _translate("LabToolWindow", "Line"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.input_channel), _translate("LabToolWindow", "Input Channel (Vi)"))
        self.label_10.setText(_translate("LabToolWindow", "Bandwidth Limit"))
        self.label_11.setText(_translate("LabToolWindow", "Coupling"))
        self.label_12.setText(_translate("LabToolWindow", "Probe"))
        self.output_coupling.setItemText(0, _translate("LabToolWindow", "DC"))
        self.output_coupling.setItemText(1, _translate("LabToolWindow", "AC"))
        self.output_probe.setItemText(0, _translate("LabToolWindow", "10"))
        self.output_probe.setItemText(1, _translate("LabToolWindow", "1"))
        self.label_25.setText(_translate("LabToolWindow", "Source"))
        self.output_source.setCurrentText(_translate("LabToolWindow", "Channel 2"))
        self.output_source.setItemText(0, _translate("LabToolWindow", "Channel 1"))
        self.output_source.setItemText(1, _translate("LabToolWindow", "Channel 2"))
        self.output_source.setItemText(2, _translate("LabToolWindow", "Channel 3"))
        self.output_source.setItemText(3, _translate("LabToolWindow", "Channel 4"))
        self.output_source.setItemText(4, _translate("LabToolWindow", "Channel 5"))
        self.output_source.setItemText(5, _translate("LabToolWindow", "Channel 6"))
        self.output_source.setItemText(6, _translate("LabToolWindow", "External"))
        self.output_source.setItemText(7, _translate("LabToolWindow", "Line"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.output_channel), _translate("LabToolWindow", "Output Channel (Vo)"))
        self.label_13.setText(_translate("LabToolWindow", "Trigger Source"))
        self.label_14.setText(_translate("LabToolWindow", "Trigger Slope"))
        self.label_15.setText(_translate("LabToolWindow", "Trigger Sweep"))
        self.label_16.setText(_translate("LabToolWindow", "Trigger Level"))
        self.trigger_source.setItemText(0, _translate("LabToolWindow", "Channel 1"))
        self.trigger_source.setItemText(1, _translate("LabToolWindow", "Channel 2"))
        self.trigger_source.setItemText(2, _translate("LabToolWindow", "Channel 3"))
        self.trigger_source.setItemText(3, _translate("LabToolWindow", "Channel 4"))
        self.trigger_source.setItemText(4, _translate("LabToolWindow", "Channel 5"))
        self.trigger_source.setItemText(5, _translate("LabToolWindow", "Channel 6"))
        self.trigger_source.setItemText(6, _translate("LabToolWindow", "External"))
        self.trigger_source.setItemText(7, _translate("LabToolWindow", "Line"))
        self.trigger_slope.setItemText(0, _translate("LabToolWindow", "Positive"))
        self.trigger_slope.setItemText(1, _translate("LabToolWindow", "Negative"))
        self.trigger_slope.setItemText(2, _translate("LabToolWindow", "Either"))
        self.trigger_slope.setItemText(3, _translate("LabToolWindow", "Alternate"))
        self.trigger_sweep.setItemText(0, _translate("LabToolWindow", "Auto"))
        self.trigger_sweep.setItemText(1, _translate("LabToolWindow", "Normal"))
        self.trigger_hf_reject.setText(_translate("LabToolWindow", "HFReject"))
        self.trigger_n_reject.setText(_translate("LabToolWindow", "NReject"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.trigger), _translate("LabToolWindow", "Trigger"))
        self.label_17.setText(_translate("LabToolWindow", "Input Peak to Peak (VPP)"))
        self.label_18.setText(_translate("LabToolWindow", "Delay between VISA commands (s)"))
        self.label_20.setText(_translate("LabToolWindow", "Start Frequency (Hz)"))
        self.label_21.setText(_translate("LabToolWindow", "Stop Frequency (Hz)"))
        self.label_22.setText(_translate("LabToolWindow", "Number of samples"))
        self.label_23.setText(_translate("LabToolWindow", "Establishment Time (s)"))
        self.label_19.setText(_translate("LabToolWindow", "Scale"))
        self.scale.setItemText(0, _translate("LabToolWindow", "Log"))
        self.scale.setItemText(1, _translate("LabToolWindow", "Linear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.bode), _translate("LabToolWindow", "Bode Preferences"))
        self.settings_back.setText(_translate("LabToolWindow", "Back"))
        self.setting_status.setText(_translate("LabToolWindow", "Settings are needed before we start measuring..."))
        self.measure.setText(_translate("LabToolWindow", "Measure"))
        self.label_6.setText(_translate("LabToolWindow", "Measure Output"))
        self.previewBox.setTitle(_translate("LabToolWindow", "Preview"))
        self.logger.setHtml(_translate("LabToolWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Test</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.measure_back.setText(_translate("LabToolWindow", "Back"))
        self.stop.setText(_translate("LabToolWindow", "Stop"))
        self.export_excel.setText(_translate("LabToolWindow", "Export .xls"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LabToolWindow = QtWidgets.QMainWindow()
    ui = Ui_LabToolWindow()
    ui.setupUi(LabToolWindow)
    LabToolWindow.show()
    sys.exit(app.exec_())

